[project]
name = "diffusion-maps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.5.0",
    "diffusers>=0.29.0",
    "einops>=0.8.2",
    "image-reward>=1.5",
    "matplotlib>=3.10.8",
    "pillow>=12.1.0",
    "protobuf>=6.33.5",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.1",
    "torchvision>=0.25.0",
    "transformers>=5.1.0",
]
